// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Category struct {
	ID         string    `json:"id"`
	Name       string    `json:"name"`
	LastUpdate time.Time `json:"lastUpdate"`
}

type Mutation struct {
}

type NewCategory struct {
	Name string `json:"name"`
}

type Query struct {
}
